markdown:         rdiscount
pygments:         true
paginate:         4

title:            Jeff Peng
url:              http://www.pengjf.com
feed:             /atom.xml
author:
    name:         Jeff
    email:        pjf.sysu@gmail.com
    description:  "The theme of this blog is designed by PIZn redesigned by me."

about:            "I am Jeff. This is my blog"
follow:
    email:        pjf.sysu@gmail.com
    github:       https://github.com/pjf000
    twitter:      http://www.twitter.com
    google:       https://plus.google.com/
    facebook:     http://facebook.com/
description:      Jeff's blog, designed base on jekyll+github  

indexContent:     true
imageLink:        http://www.pizn.net/static/images/20121109Monutain.jpg


style:            /css/style.css
blogName:         Jeff's Blog 
blogDesc:         Just copy from bizn
favicon:          /favicon.ico
theme:            default

disqus:           jeffblog

copyright:        Copyright © 2013-2014 Jeff Peng All rights reserved.
test:             ok
